### ISSUE TITLE
Anaconda

### ISSUE THREAD

**Issue by nosratullah** [stsievert/python-drawnow#6] opened 2017-11-10 19:27 UTC
Hi, 
Is there any way to install this package on Anaconda?

**Comment by stsievert** [comment] 2017-11-10 19:36
> on Anaconda?

You mean with the `conda` command? No, because it only requires matplotlib >= 1.5.

`pip` is included in the default Anaconda package. Why not use that?

**Comment by nosratullah** [comment] 2017-11-21 00:35
I did use that but when I use  jupyter from Anaconda, jupyter could not load this package.

**Comment by stsievert** [comment] 2017-11-21 00:41
> jupyter could not load this package.

What do you mean by that? Does this package not work in the Jupyter Notebook?

**Comment by nosratullah** [comment] 2017-11-21 00:43
Yes, exactly. I installed this with pip but it doesn't work in jupyter.

**Comment by stsievert** [comment] 2017-11-21 00:57
I'm pretty sure I wouldn't expect it to work in the notebook with the default backed.

If you want this in the notebook, try using

``` python
import matplotlib as mpl
mpl.use('WebAgg', warn=False, force=True)
```

You can see a list of available backends with `mpl.rcsetup.interactive_bk`. This will pop a separate window outside of the notebook that shows your plot.

(helped by [this SO answer](https://stackoverflow.com/questions/3285193/how-to-switch-backends-in-matplotlib-python/43015816#43015816))

**Comment by stsievert** [comment] 2018-01-31 03:14
I think this is the issue is "I installed package X and now I can't import it in the notebook. Help!", which is the motivation for this post: https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/index.html

I'm closing this issue because I don't think it's an issue with this package but a problem with configuration (but I'm willing to keep talking about it).

**Closed as completed by stsievert** 2018-01-31 03:14 UTC
